source 'https://rubygems.org'
ruby '2.1.2'

gem 'sinatra'

gem 'unicorn'
gem 'haml'
gem 'compass'
gem 'activesupport'
gem 'builder'
gem 'i18n'
gem 'will_paginate', '~> 3.0.0'
gem 'mingo'
gem 'activemodel'
gem 'mongo', '~> 1.12.0'
gem 'mongo_ext'
gem 'bson_ext'
gem 'faraday_middleware'
gem 'choices'
gem 'rake'
gem 'never-forget'
gem 'dalli'
gem 'metriks-middleware'
gem 'rack-cache'
